### ISSUE TITLE
New Resource: Oregon dropping AI tool used in child abuse cases

### ISSUE THREAD

**Issue by parulnith** [romanlutz/ResponsibleAI#5]
Hi,
I wanted to mention a recent article titled [Oregon dropping AI tool used in child abuse cases](https://www.lagrandeobserver.com/news/state/oregon-dropping-ai-tool-used-in-child-abuse-cases/article_95e7ea7e-e289-11ec-8393-a3d73b38be3d.html) where the agencies have decided to do away with the AI algorithmic system inorder to reduce disparities concerning which families are investigated for child abuse and neglect by child protective services.

**Comment by romanlutz** [comment]
@parulnith this definitely fits the bill! I've stopped adding to this list in favor of adding it to https://incidentdatabase.ai/?lang=en ? You can do the quick add on that page or go to https://incidentdatabase.ai/apps/submit and get credit for submitting it 🙂 
If you don't want to go through that, please let me know and I'll add it.

**Comment by parulnith** [comment]
Thanks for letting me know @romanlutz. I submitted the incident via the incident database. I might have more incidents to report in the future since I'm co-authoring a book on a similar topic: [ML or high-risk applications](https://learning.oreilly.com/library/view/machine-learning-for/9781098102425/) 🙂

**Comment by romanlutz** [comment]
Oh, this looks very interesting! The incident database is quite awesome and also open source, by the way! Thanks for contributing it there 🙂
